=== Build

==== Windows

===== Windows 10

The only supported build platform for Windows is version 10 other releases
have not been tested.

====== Clone repositories

[source,console,subs=attributes]
----
git clone {git-base-url}/PortableApps.comInstaller.git
git clone -b patched https://github.com/uroesch/PortableApps.comLauncher.git
git clone {git-base-url}/{app-name}.git
----

====== Build installer

[source,console,subs=attributes]
----
cd {app-name}
powershell -ExecutionPolicy ByPass -File Other/Update/Update.ps1
----

==== Linux

===== Docker

[NOTE]
This is currently the preferred way of building the PortableApps installer.

For a Docker build run the following command.

====== Clone repo

[source,console,subs=attributes]
----
git clone {git-base-url}/{app-name}.git
----

====== Build installer

[source,console,subs=attributes]
----
cd {app-name}
curl -sJL https://raw.githubusercontent.com/uroesch/PortableApps/master/scripts/docker-build.sh | bash
----

==== Local build

===== Ubuntu 20.04

To build the installer under Ubuntu 20.04 `Wine`, `PowerShell`, `7-Zip` and
when building headless `Xvfb` are required.

====== Setup

[source,console]
----
sudo snap install powershell --classic
sudo apt --yes install git wine p7zip-full xvfb
----

When building headless run the below command starts a virtual Xserver required
for the build to succeed.

[source,console]
----
export DISPLAY=:7777
Xvfb ${DISPLAY} -ac &
----

====== Clone repositories

[source,console,subs=attributes]
----
git clone {git-base-url}/PortableApps.comInstaller.git
git clone -b patched {git-base-url}/PortableApps.comLauncher.git
git clone {git-base-url}/{app-name}.git
----

====== Build installer

[source,console,subs=attributes]
----
cd {app-name}
pwsh Other/Update/Update.ps1
----

===== Ubuntu 18.04

To build the installer under Ubuntu 18.04 `Wine`, `PowerShell`, `7-Zip` and
when building headless `Xvfb` are required.

====== Setup

[source,console]
----
sudo snap install powershell --classic
sudo apt --yes install git p7zip-full xvfb
sudo dpkg --add-architecture i386
sudo apt update
sudo apt --yes install wine32
----

When building headless run the below command starts a virtual Xserver required
for the build to succeed.

[source,console]
----
export DISPLAY=:7777
Xvfb ${DISPLAY} -ac &
----

====== Clone repositories

[source,console,subs=attributes]
----
git clone {git-base-url}/PortableApps.comInstaller.git
git clone -b patched {git-base-url}/PortableApps.comLauncher.git
git clone {git-base-url}/{app-name}.git
----

====== Build installer

[source,console,subs=attributes]
----
cd {app-name}
pwsh Other/Update/Update.ps1
----
