# -----------------------------------------------------------------------------
# Sync CommonFiles daily
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.2.0
# -----------------------------------------------------------------------------
name: daily-commonfiles-sync

on:
  push:
    branches:
    - workflow/*
  #schedule:
  #  - cron: '20 2 * * *' # Sync submodules daily
  workflow_dispatch:

jobs:
  daily-commonfiles-sync:
    timeout-minutes: 90
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
        - ubuntu-latest

    steps:
    - name: Setup git
      shell: bash
      run: |2+
        git config --global user.name "Urs Roesch"
        git config --global user.email "github@bun.ch"
        git config --global pull.rebase true

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: master
        token: ${{ secrets.PA_ACTION_TOKEN }}
        submodules: recursive

    - name: Update common files
      shell: bash
      env:
         GITHUB_TOKEN: ${{ secrets.PA_ACTION_TOKEN }}
         GITHUB_USER: ${{ github.actor }}
      run: |2+
        git config --global url."https://${GITHUB_USER}@github.com:".insteadOf "https://github.com/"
        bash ./scripts/sync-common-files.sh --template
        bash -x ./scripts/sync-common-files.sh --docker
