# -----------------------------------------------------------------------------
# Sync CommonFiles daily
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.2.0
# -----------------------------------------------------------------------------
name: daily-commonfiles-sync

on:
  push:
    branches:
    - workflow/*
  #schedule:
  #  - cron: '20 2 * * *' # Sync submodules daily
  workflow_dispatch:

jobs:
  daily-commonfiles-sync:
    timeout-minutes: 90
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
        - ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: master
        submodules: recursive

    - name: Setup git
      shell: bash
      run: |2+
        set -x
        git config --global user.name "Urs Roesch"
        git config --global user.email "github@bun.ch"
        git config --global pull.rebase true

    - name: Show remote
      shell: bash
      run: |2+
        git config --get-regex 'remote\..*'

    - name: Update common files
      shell: bash
      run: bash ./scripts/sync-common-files.sh --docker
